In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
# I only take Corporate and AAA- AA3
rating= ['AAA IS', 'AA3', 'A1', 'AAA', 'A+ IS', 'AAA (S)',
       'AA2 (S)', 'AA1', 'AA2', 'AA1 (S)', 'AA+ IS','AA+', 'AA IS', 'AAA IS (FG)', 'AAA (FG)', 'AAA (BG)', 'A3',
       'AA- IS', 'A1 (S)', 'AA-','A IS', 'A-','AA3 (S)', 'A- IS', 'AA- IS (CG)', 'A2', 'AA', 'A+ IS (S)', 'A2 (S)']

In [22]:
value_files = ['201907/BPAMERP20190731.csv','201908/BPAMERP20190830.csv','201909/BPAMERP20190930.csv',
            '201910/BPAMERP20191031.csv','201911/BPAMERP20191129.csv','201912/BPAMERP20191231.csv','202001/BPAMERP20200131.csv',
            '202002/BPAMERP20200228.csv','202003/BPAMERP20200331.csv','202004/BPAMERP20200430.csv',
            '202005/BPAMERP20200529.csv','202006/BPAMERP20200630.csv','202007/BPAMERP20200730.csv',
            '202008/BPAMERP20200828.csv','202009/BPAMERP20200930.csv','202010/BPAMERP20201030.csv']
type_files = ['201907/BPAMERS20190731.csv','201908/BPAMERS20190830.csv','201909/BPAMERS20190930.csv',
            '201910/BPAMERS20191031.csv','201911/BPAMERS20191129.csv','201912/BPAMERS20191231.csv','202001/BPAMERS20200131.csv',
            '202002/BPAMERS20200228.csv','202003/BPAMERS20200331.csv','202004/BPAMERS20200430.csv',
            '202005/BPAMERS20200529.csv','202006/BPAMERS20200630.csv','202007/BPAMERS20200730.csv',
            '202008/BPAMERS20200828.csv','202009/BPAMERS20200930.csv','202010/BPAMERS20201030.csv']


df=pd.DataFrame()

for v,t in zip(value_files,type_files):
    df_temp = pd.read_csv('./BPAM Evaluated Prices Rated Range Prices (LT)/'+v)
    df_tempT = pd.read_csv('./BPAM Evaluated Prices Rated Range Prices (LT)/'+t)
    df_temp= df_temp.merge(df_tempT,on='STOCK CODE')
    df_temp = df_temp[df_temp['BOND CLASS']=='Corporate'][df_temp['RATING'].isin(rating)]
    
    if df.empty:
        df= df_temp
    else:
        df= df.append(df_temp)

<ipython-input-22-a02b152b28aa>:19: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_temp = df_temp[df_temp['BOND CLASS']=='Corporate'][df_temp['RATING'].isin(rating)]

In [23]:
df.head()

,STOCK CODE,ISIN CODE_x,STOCK NAME_x,VALUE DATE,EVAL UPPER THRESHOLD YIELD,EVAL MID YIELD,EVAL LOWER THRESHOLD YIELD,EVAL LOWER THRESHOLD PRICE,EVAL MID PRICE,EVAL UPPER THRESHOLD PRICE,...,BOND CURRENT OUTSTANDING AMOUNT(MYR MIL),REMAINING TENURE,ISSUER FACILITY LIMIT(MYR MIL),ISSUER OUTSTANDING AMOUNT(MYR MIL),ISLAMIC CONCEPT,SECTOR,RATING EFFECTIVE DATE,CALLABLE/PUTTABLE,CONVERTIBLE/EXCHANGABLE,RATING ACTION
44,DZ012851,MYBDZ0128511,TENAGA IBONDS 0.00000% 13.12.2021,01-AUG-2019,3.431,3.392,3.353,108.263,108.356,108.448,...,2000,3Y,16000,7000,BAI BITHAMAN AJIL,INFRASTRUCTURES AND UTILITIES,12-APR-2019,N,N,Affirm
45,DZ021250,MYBDZ0212505,GDC PUTRA 0.00000% 02.12.2022,01-AUG-2019,3.724,3.680,3.636,110.959,111.105,111.251,...,50,5Y,300,50,BAI BITHAMAN AJIL,INFRASTRUCTURES AND UTILITIES,31-OCT-2018,N,N,Affirm
63,VP070896,MYBVP0708968,JEV IMTN 0% 12.11.2019,01-AUG-2019,3.572,3.521,3.470,101.553,101.568,101.583,...,70,3M,4847,1700,ISTISNA,INFRASTRUCTURES AND UTILITIES,26-DEC-2018,N,N,Reaffirm
64,VR060698,MYBVR0606986,JEV IMTN 0% 12.11.2019,01-AUG-2019,3.577,3.521,3.465,101.456,101.472,101.488,...,20,3M,4847,1700,ISTISNA,INFRASTRUCTURES AND UTILITIES,26-DEC-2018,N,N,Reaffirm
65,VQ061773,MYBVQ0617738,JEV IMTN 0% 12.11.2019,01-AUG-2019,3.577,3.521,3.465,101.497,101.513,101.529,...,50,3M,4847,1700,ISTISNA,INFRASTRUCTURES AND UTILITIES,26-DEC-2018,N,N,Reaffirm

In [24]:
df.shape

(15319, 51)

In [25]:
df.groupby(['CALLABLE/PUTTABLE'])['STOCK CODE'].count()

CALLABLE/PUTTABLE
N    14604
Y      715
Name: STOCK CODE, dtype: int64

In [26]:
df['VALUE DATE']=pd.to_datetime(df['VALUE DATE'])
df['MATURITY DATE']=pd.to_datetime(df['MATURITY DATE'])
df['ISSUE DATE']=pd.to_datetime(df['ISSUE DATE'])

In [27]:
df= df.sort_values(['STOCK CODE','VALUE DATE'])

In [28]:
df_clean = df[['STOCK CODE','STOCK NAME_x', 'VALUE DATE', 'EVAL MID YIELD',
       'EVAL MID PRICE','MODIFIED DURATION','CONVEXITY','COMPOSITE LIQUIDITY SCORE (T-1)',
       'BOND TYPE', 'RATING','ISSUE DATE', 'MATURITY DATE', 'COUPON FREQUENCY', 
       'NEXT COUPON RATE', 'FACILITY AMOUNT/FACILITY LIMIT(MYR MIL)',
       'FACILITY OUTSTANDING AMOUNT(MYR MIL)', 'BOND ISSUE AMOUNT(MYR MIL)','REMAINING TENURE',
       'BOND CURRENT OUTSTANDING AMOUNT(MYR MIL)','ISSUER FACILITY LIMIT(MYR MIL)', 'ISSUER OUTSTANDING AMOUNT(MYR MIL)',
       'SECTOR','CALLABLE/PUTTABLE']]

### Replacing Y / N in last two column with 1 / 0

In [29]:
df_clean['CALLABLE/PUTTABLE'].replace({'Y':1,'N':0},inplace=True)

C:\Users\jowen\anaconda3\lib\site-packages\pandas\core\series.py:4509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

In [30]:
df_clean.head()

,STOCK CODE,STOCK NAME_x,VALUE DATE,EVAL MID YIELD,EVAL MID PRICE,MODIFIED DURATION,CONVEXITY,COMPOSITE LIQUIDITY SCORE (T-1),BOND TYPE,RATING,...,NEXT COUPON RATE,FACILITY AMOUNT/FACILITY LIMIT(MYR MIL),FACILITY OUTSTANDING AMOUNT(MYR MIL),BOND ISSUE AMOUNT(MYR MIL),REMAINING TENURE,BOND CURRENT OUTSTANDING AMOUNT(MYR MIL),ISSUER FACILITY LIMIT(MYR MIL),ISSUER OUTSTANDING AMOUNT(MYR MIL),SECTOR,CALLABLE/PUTTABLE
1282,DI140013,UNITAPAH 5.06% Series 8 12.12.2019,2019-08-01,3.581,100.521,0.358,0.257,0.0,Fixed Rate Bond,AA1,...,5.06,600,410,10,6M,10,600,410,CONSTRUCTION AND ENGINEERING,0
1270,DI140013,UNITAPAH 5.06% Series 8 12.12.2019,2019-09-03,3.517,100.406,0.270,0.146,0.0,Fixed Rate Bond,AA1,...,5.06,600,410,10,3M,10,600,410,CONSTRUCTION AND ENGINEERING,0
1256,DI140013,UNITAPAH 5.06% Series 8 12.12.2019,2019-10-01,3.429,100.307,0.195,0.076,0.0,Fixed Rate Bond,AA1,...,5.06,600,410,10,3M,10,600,410,CONSTRUCTION AND ENGINEERING,0
1257,DI140013,UNITAPAH 5.06% Series 8 12.12.2019,2019-11-01,3.435,100.172,0.111,0.024,0.0,Fixed Rate Bond,AA1,...,5.06,600,410,10,3M,10,600,410,CONSTRUCTION AND ENGINEERING,0
1252,DI140013,UNITAPAH 5.06% Series 8 12.12.2019,2019-12-02,3.404,100.041,0.026,0.001,0.0,Fixed Rate Bond,AA1,...,5.06,600,410,10,3M,10,600,410,CONSTRUCTION AND ENGINEERING,0

In [31]:
df_clean.to_csv('combined_data.csv',index=False)

In [32]:
df_clean.shape

(15319, 23)

### Stock i want to visualize , insert STOCK CODE

In [33]:
plt.figure(figsize=(16,8))
df_v = df_clean[df_clean['STOCK CODE']=='DM140033']
df_v.head()

,STOCK CODE,STOCK NAME_x,VALUE DATE,EVAL MID YIELD,EVAL MID PRICE,MODIFIED DURATION,CONVEXITY,COMPOSITE LIQUIDITY SCORE (T-1),BOND TYPE,RATING,...,NEXT COUPON RATE,FACILITY AMOUNT/FACILITY LIMIT(MYR MIL),FACILITY OUTSTANDING AMOUNT(MYR MIL),BOND ISSUE AMOUNT(MYR MIL),REMAINING TENURE,BOND CURRENT OUTSTANDING AMOUNT(MYR MIL),ISSUER FACILITY LIMIT(MYR MIL),ISSUER OUTSTANDING AMOUNT(MYR MIL),SECTOR,CALLABLE/PUTTABLE
1290,DM140033,UNITAPAH 5.49% Series 16 12.12.2023,2019-08-01,3.964,106.054,3.851,17.737,0.0,Fixed Rate Bond,AA1,...,5.49,600,410,15,5Y,15,600,410,CONSTRUCTION AND ENGINEERING,0
1278,DM140033,UNITAPAH 5.49% Series 16 12.12.2023,2019-09-03,3.758,106.772,3.768,17.065,0.0,Fixed Rate Bond,AA1,...,5.49,600,410,15,5Y,15,600,410,CONSTRUCTION AND ENGINEERING,0
1264,DM140033,UNITAPAH 5.49% Series 16 12.12.2023,2019-10-01,3.782,106.564,3.692,16.461,0.0,Fixed Rate Bond,AA1,...,5.49,600,410,15,5Y,15,600,410,CONSTRUCTION AND ENGINEERING,0
1265,DM140033,UNITAPAH 5.49% Series 16 12.12.2023,2019-11-01,3.802,106.364,3.608,15.807,0.0,Fixed Rate Bond,AA1,...,5.49,600,410,15,5Y,15,600,410,CONSTRUCTION AND ENGINEERING,0
1260,DM140033,UNITAPAH 5.49% Series 16 12.12.2023,2019-12-02,3.793,106.280,3.525,15.174,0.0,Fixed Rate Bond,AA1,...,5.49,600,410,15,5Y,15,600,410,CONSTRUCTION AND ENGINEERING,0

### Bond price over time

In [34]:
plt.plot(df_v['VALUE DATE'],df_v['EVAL MID PRICE']);
plt.xlabel('Value Date');
plt.ylabel('Price');

### Yield (YTM) over time

In [35]:
plt.plot(df_v['VALUE DATE'],df_v['EVAL MID YIELD']);
plt.xlabel('Value Date');
plt.ylabel('Yield')

Text(144.84722222222223, 0.5, 'Yield')

### High liquidity indicates its ability to pay debt obligations, or current liabilities, without having to raise external capital or take out loans.

In [36]:
plt.plot(df_v['VALUE DATE'],df_v['COMPOSITE LIQUIDITY SCORE (T-1)']);
plt.xlabel('Value Date');
plt.ylabel('COMPOSITE LIQUIDITY SCORE');

### Convexity = the degree of the curve, in the relationship between bond prices and bond yields.

In [37]:
plt.plot(df_v['VALUE DATE'],df_v['CONVEXITY']);
plt.xlabel('Value Date');
plt.ylabel('CONVEXITY');